- name: install packages
  apt: name={{item}} state=installed default_release=jessie-backports #update_cache=yes 
  with_items:
    - haproxy

- name: Make download dir writable for pi user
  file: path={{ install_dir }}/haproxy/conf state=directory owner=pi group=adm mode=0774

- name: Copy haproxy config templates
  template: src=configs/{{ item }} dest={{ install_dir }}/haproxy/conf/{{ item }}
  with_items:
  - haproxy.cfg

- name: Get last haproxy pid
  command: "cat /opt/neo4j/haproxy.pid"
  ignore_errors: yes
  register: haproxy_pid

- name: Start haproxy
  shell: /usr/sbin/haproxy -f /opt/neo4j/haproxy/conf/haproxy.cfg -p /opt/neo4j/haproxy.pid -st {{ haproxy_pid.stdout }}